githubConfigUrl: "https://github.com/mantavya-se"
githubConfigSecret: pre-defined-secret
runnerGroup: self-hosted-runner
template:
  spec:
    imagePullSecrets:
    - name: ecr-pull-secret
    securityContext:
      fsGroup: 988
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock

    volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket