name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - "docker/runner/**"
    - ".github/workflows/build-image.yaml"
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: secure-ci-ecr
  IMAGE_TAG: latest
  AWS_ACCOUNT_ID: 835577334660

jobs:
  build:
    runs-on: arc-runner-set
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
    
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region "$AWS_REGION" | \
          docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
    
    - name: Build runner Image
      run: |
        docker build -t "$ECR_REPOSITORY"  docker/runner
    
    - name: Tag Image
      run: |
        docker tag "$ECR_REPOSITORY:$IMAGE_TAG" \
            "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
    
    - name: Push image to ECR
      run: |
        docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
    
    - name: Upgrade arc runner set
      run: |
        ECR_IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
        helm upgrade arc-runner-set \
          --namespace arc-runners \
          --set githubConfigUrl="https://github.com/MantavyaS/secure-self-hosted-ci-platform" \
          --set githubConfigSecret=pre-defined-secret \
          --set template.spec.containers[0].name=runner \
          --set template.spec.containers[0].image="$ECR_IMAGE_URI" \
          --set-json 'template.spec.containers[0].command=["/home/runner/run.sh"]' \
          oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
      


