name: Validate runner image
on:
  workflow_dispatch:

jobs:
  Validate:
    runs-on: arc-runner-set

    steps:
    - run: |
        aws --version
        docker --version
        helm version
        terraform version